### ISSUE TITLE
Upstream `hookable` issue

### ISSUE THREAD

**Issue by AndreyYolkin** [nuxt/bridge#1000]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.10.5
- Builder:          webpack
- User Config:      app, components, modules, plugins, nitro, vite, bridge, runtimeConfig, serverHandlers, devServerHandlers, devServer, typescript, buildModules
- Runtime Modules:  ()
- Build Modules:    (), @nuxt/bridge@3.0.0-rc.4
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dwx287-swerdg?file=pages%2Findex.vue,modules%2Fprimary%2Findex.ts

### Describe the bug

As mentioned in https://github.com/nuxt/nuxt/issues/24419, Nuxt prior to upcoming 2.17.3 utilises `hable` package, which doesn't have some features, like unsubscribing from hooks. Nuxt 2.17.3 will use `hookable` v4, but bridge has v5 in its dependencies.

At least, we should downgrade and lock `hookable` version to v4.
Also we need to decide:
1) Provide support in bridge codebase for nuxt 2.17.2 or lower.
2) Raise minimum required version to 2.17.3

### Logs

```
 FATAL  unsub is not a function

  at eval (node_modules/nuxi/dist/chunks/dev2.mjs:272:7)
  at eval (node_modules/hable/dist/hable.js:1:1065)
  at eval (node_modules/hable/dist/hable.js:1:283)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:1034)
```

**Comment by danielroe** [comment]
@wattanx this is closed by https://github.com/nuxt/bridge/pull/1025, right?

**Comment by wattanx** [comment]
Yes! #1025 resolved this issue.

**Comment by suits-at** [comment]
I just came across this (already closed) issue because I think actually, it's still (or maybe again?) an issue. Just as mentioned in the description above, now there is hookable v4 in nuxt 2.17.3 and v5 in stable bridge. Therefore if you now try to `pnpm i && pnpm run dev` you will get a SyntaxError saying `The requested module 'PATH/hookable.js' does not provide an export named 'createHooks'`. With NPM it does work by the way, so seems to be related to how PNPM handles different versions of the same package. Downgrading nuxt to 2.17.2 also solves the issue, as there is no hookable v4 in use then.
Can you confirm this @wattanx or did I miss something?

**Comment by wattanx** [comment]
@suits-at 
Could you please create a new issue so I might miss it?
(Probably needs to be fixed)

**Comment by suits-at** [comment]
> @suits-at Could you please create a new issue so I might miss it? (Probably needs to be fixed)

Sure. Here you go: https://github.com/nuxt/bridge/issues/1078
